# =========================================================
# Application
# =========================================================

spring.application.name=user-service

# =========================================================
# Config Server
# =========================================================

spring.config.import=configserver:http://localhost:8888

# =========================================================
# Profile
# =========================================================

spring.profiles.active=dev